# Generated by Django 5.2.5 on 2025-08-12 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TriviaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_code', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TriviaResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=1000)),
                ('correct_answer', models.CharField(max_length=1000)),
                ('incorrect_answers', models.JSONField()),
                ('trivia_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='app.triviaquestion')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('answered_trivia_questions', models.ManyToManyField(blank=True, related_name='answered_by', to='app.triviaquestion')),
            ],
        ),
    ]
